src/Web/NetPhlixDB.Web/Areas/Admin/Controllers/PeopleController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetPhlixDb.Data.ViewModels.Admin.People;
using NetPhlixDB.Data;
using NetPhlixDB.Data.Models;

namespace NetPhlixDB.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PeopleController : Controller
    {
        private readonly NetPhlixDbContext _context;
        private readonly IMapper _mapper;

        public PeopleController(NetPhlixDbContext context, IMapper mapper)
        {
            this._context = context;
            this._mapper = mapper;
        }
        
        public async Task<IActionResult> Index()
        {
            var people = await _context.People.ToListAsync();
            var peopleViewModel = this._mapper.Map<IEnumerable<Person>, IEnumerable<IndexPersonViewModel>>(people);

            return View(peopleViewModel);
        }
        
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.People
                .FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(CreatePersonViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var person = this._mapper.Map<CreatePersonViewModel, Person>(viewModel);
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        // GET: Admin/People/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.People.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }

            var personViewModel = this._mapper.Map<Person, EditPersonViewModel>(person);
            return View(personViewModel);
        }
        
        [HttpPost]
        public async Task<IActionResult> Edit(string id, EditPersonViewModel viewModel)
        {
            if (id != viewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var person = this._mapper.Map<EditPersonViewModel, Person>(viewModel);
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }
        
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.People
                .FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }
        
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var person = await _context.People.FindAsync(id);
            _context.People.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(string id)
        {
            return _context.People.Any(e => e.Id == id);
        }
    }
}

src/Web/NetPhlixDB.Web/Controllers/MoviesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetPhlixDB.Services.Contracts;
using NetPhlixDB.Web.Common;

namespace NetPhlixDB.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly IUsersService _usersService;

        public MoviesController(IMoviesService moviesService, IUsersService usersService)
        {
            this._moviesService = moviesService;
            this._usersService = usersService;
        }

        [Authorize]
        public async Task<IActionResult> All(int? currentPage = 1, string search = "", string genre = "", string sortOrder = "")
        {
            ViewData["NameSortParm"] = sortOrder == "name" ? "name_desc" : "name";
            ViewData["DateSortParm"] = sortOrder == "date" ? "date_desc" : "date";
            ViewData["CurrentFilter"] = search;
            ViewData["CurrentGenre"] = genre;

            var paginationMoviesViewModel = await this._moviesService.GetPageMovies(currentPage, search, genre, sortOrder);

            return this.View(paginationMoviesViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            var movieExists = await this._moviesService.MovieExists(id);
            if (!movieExists)
            {
                return this.NotFound();
            }

            var movieViewModel = await this._moviesService.GetById(id);
            movieViewModel.UserFavoriteMovies = await this._usersService.GetFavoriteMoviesList(this.User.Identity.Name);

            return this.View(movieViewModel);
        }
    }
}

src/Web/NetPhlixDB.Web/Controllers/PeopleController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetPhlixDB.Services.Contracts;

namespace NetPhlixDB.Web.Controllers
{
    public class PeopleController : Controller
    {
        private readonly IPeopleService _peopleService;

        public PeopleController(IPeopleService peopleService)
        {
            this._peopleService = peopleService;
        }

        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            var personViewModel = await this._peopleService.GetById(id);

            if (personViewModel == null)
            {
                return this.NotFound();
            }

            return View(personViewModel);
        }

        [Authorize]
        public async Task<IActionResult> All()
        {
            var people = await this._peopleService.GetAll();

            return this.View(people);
        }
    }
}

src/Web/NetPhlixDB.Web/Views/People/All.cshtml
@model IEnumerable<NetPhlixDb.Data.ViewModels.People.PersonViewModel>

@{
    ViewData["Title"] = "Celebrities";
}

<div class="container w-75">
    <h1 class="text-center mt-3 mb-3 text-info">Celebrities</h1>
    <table class="table table-striped text-center">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Picture</th>
                <th scope="col">Name</th>
                <th scope="col">Birth Date</th>
                <th scope="col">Profession</th>
                <th scope="col">Birth Place</th>
            </tr>
        </thead>
        <tbody>
        @{ var index = 1;}
        @foreach (var p in Model)
        {
            <tr>
                <th scope="row">@index</th>
                <td><a asp-controller="People" asp-action="Details" asp-route-id="@p.Id"><img class="img-fluid" style="height: 70px; width: 70px" src="@p.Picture" /></a></td>
                <td><a asp-controller="People" asp-action="Details" asp-route-id="@p.Id">@p.Name</a></td>
                <td>@p.BirthDate.ToString("MMM/dd/yyyy")</td>
                <td>@p.Role</td>
                <td>@p.BirthPlace</td>
            </tr>
            {
                index++;
            }
        }
        </tbody>
    </table>
    <div class="text-center">
        <a class="btn btn-primary w-25 mt-2 mb-2" href="##" onClick="history.go(-1); return false;">Back</a>
    </div>
</div>

src/Web/NetPhlixDB.Web/Views/People/Details.cshtml
@model NetPhlixDb.Data.ViewModels.People.PersonViewModel

@{
    ViewData["Title"] = "Celebrity Details";
}

<div class="container w-75">
    <h2 class="text-center mb-4 mt-4 text-info">@Model.Name</h2>
    <div class="card mx-auto" style="width: 28rem;">
        <img class="card-img-top" src="@Model.Picture" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">@Model.Name - @Model.Role</h5>
            <p class="card-text text-justify">@Model.Bio</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong>Birth date</strong>: @Model.BirthDate.ToString("MMM/dd/yyyy")</li>
            <li class="list-group-item"><strong>Birth place</strong>: @Model.BirthPlace</li>
        </ul>
        @*<div class="card-body">
            <a href="#" class="card-link">@Model.</a>
            <a href="#" class="card-link">Another link</a>
        </div>*@
    </div>
    <h4 class="text-center mt-4 mb-1">Known for</h4>
    @{ var pMovies = Model.PersonMovieViewModels;}
    @for (int i = 0; i < pMovies.Count; i += 2)
    {
        <div class="row mx-auto w-75">
            @for (int k = 0; k <= 1 && k + i < pMovies.Count; k++)
            {
                <div class="col-md">
                    <div class="card border-primary mb-3 mt-3" style="max-width: 15rem;">
                        <div class="card-header">(@pMovies[k + i].DateReleased.Year)</div>
                        <div class="card-body text-primary">
                            <h5 class="card-title"><a asp-controller="Movies" asp-action="Details" asp-route-id="@pMovies[k + i].Id">@pMovies[k + i].Title</a></h5>
                            <p class="card-text">@pMovies[k + i].Storyline</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
</div>

<div class="text-center">
    <a class="btn btn-primary w-25 mt-2 mb-2" href="##" onClick="history.go(-1); return false;">Back</a>
</div>