src/Web/NetPhlixDB.Web/Areas/Admin/Controllers/CompaniesController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetPhlixDb.Data.ViewModels.Admin.Companies;
using NetPhlixDB.Data;
using NetPhlixDB.Data.Models;
using NetPhlixDB.Services.Contracts;

namespace NetPhlixDB.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompaniesController : Controller
    {
        private readonly NetPhlixDbContext _context;
        private readonly IMapper _mapper;
        private readonly ICompaniesService _companiesService;

        public CompaniesController(NetPhlixDbContext context, IMapper mapper, ICompaniesService companiesService)
        {
            this._context = context;
            this._mapper = mapper;
            this._companiesService = companiesService;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var companies = await this._companiesService.GetAll();
            
            return View(companies.OrderByDescending(x => x.CreatedOn));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(string id)
        {
            var company = await this._companiesService.GetByIdAdmin(id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            return await Task.Run(() => View());
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateCompanyViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await this._companiesService.Create(viewModel);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            var company = await this._companiesService.GetByIdAdmin(id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(string id, EditDeleteDetailsCompanyViewModel viewModel)
        {
            if (id != viewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var result = await this._companiesService.Update(viewModel);

                if (result == null)
                {
                    return this.NotFound();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyViewModel = await this._companiesService.GetByIdAdmin(id);

            if (companyViewModel == null)
            {
                return this.NotFound();
            }

            return View(companyViewModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var result = await this._companiesService.Delete(id);
            if (result == null)
            {
                return this.NotFound();
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Web/NetPhlixDB.Web/Controllers/CompaniesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NetPhlixDB.Services.Contracts;

namespace NetPhlixDB.Web.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ICompaniesService _companiesService;

        public CompaniesController(ICompaniesService companiesService)
        {
            this._companiesService = companiesService;
        }

        public async Task<IActionResult> Details(string id)
        {
            var companyDetails = await this._companiesService.GetById(id);
            
            if (companyDetails == null)
            {
                return this.NotFound();
            }

            return View(companyDetails);
        }

        public async Task<IActionResult> All()
        {
            var allCompanies = await this._companiesService.GetAll();
            
            return this.View(allCompanies);
        }
    }
}

src/Web/NetPhlixDB.Web/Controllers/MoviesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetPhlixDB.Services.Contracts;
using NetPhlixDB.Web.Common;

namespace NetPhlixDB.Web.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly IUsersService _usersService;

        public MoviesController(IMoviesService moviesService, IUsersService usersService)
        {
            this._moviesService = moviesService;
            this._usersService = usersService;
        }

        [Authorize]
        public async Task<IActionResult> All(int? currentPage = 1, string search = "", string genre = "", string sortOrder = "")
        {
            ViewData["NameSortParm"] = sortOrder == "name" ? "name_desc" : "name";
            ViewData["DateSortParm"] = sortOrder == "date" ? "date_desc" : "date";
            ViewData["CurrentFilter"] = search;
            ViewData["CurrentGenre"] = genre;

            var paginationMoviesViewModel = await this._moviesService.GetPageMovies(currentPage, search, genre, sortOrder);

            return this.View(paginationMoviesViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Details(string id)
        {
            var movieExists = await this._moviesService.MovieExists(id);
            if (!movieExists)
            {
                return this.NotFound();
            }

            var movieViewModel = await this._moviesService.GetById(id);
            movieViewModel.UserFavoriteMovies = await this._usersService.GetFavoriteMoviesList(this.User.Identity.Name);

            return this.View(movieViewModel);
        }
    }
}

src/Web/NetPhlixDB.Web/Views/Companies/All.cshtml
@model IEnumerable<NetPhlixDb.Data.ViewModels.Companies.CompanyShortViewModel>

@{
    ViewData["Title"] = "All Companies";
}
<link rel="stylesheet" type="text/css" href="~/lib/DataTables/DataTables-1.10.18/css/jquery.dataTables.min.css" />
<link href="~/lib/DataTables/Buttons-1.5.6/css/buttons.dataTables.min.css" rel="stylesheet" />

<div class="container w-75">
    <h1 class="text-center mt-3 mb-3 text-info">All Companies</h1>
    <table id="companies" class="table-condensed" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Logo</th>
                <th scope="col">Name</th>
                <th scope="col">Established</th>
            </tr>
        </thead>
        <tbody>
            @{ var index = 1;}
            @foreach (var c in Model)
            {
                var img = "";
                if (string.IsNullOrEmpty(c.Logo))
                {
                    img = "http://izuum.com/noimage.jpg";
                }
                else
                {
                    img = "https://image.tmdb.org/t/p/w500" + c.Logo;
                }
                <tr>
                    <th scope="row">@index</th>
                    <td><a asp-controller="Companies" asp-action="Details" asp-route-id="@c.Id"><img class="img-fluid" style="height: 60px; width: 50px" src="@img" /></a></td>
                    <td><a asp-controller="Companies" asp-action="Details" asp-route-id="@c.Id">@c.Name</a></td>
                    <td>@c.CreatedOn.ToString("MMM/dd/yyyy")</td>
                </tr>
                {
                    index++;
                }
            }
        </tbody>
    </table>
    <div class="text-center">
        <a class="btn btn-primary w-25 mt-2 mb-2" href="##" onClick="history.go(-1); return false;">Back</a>
    </div>
</div>

@section Scripts{

    <script type="text/javascript" src="~/lib/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/DataTables/DataTables-1.10.18/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/lib/DataTables/Buttons-1.5.6/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="~/lib/DataTables/Buttons-1.5.6/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="~/lib/DataTables/pdfmake-0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="~/lib/DataTables/pdfmake-0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="~/lib/DataTables/Buttons-1.5.6/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="~/lib/DataTables/Buttons-1.5.6/js/buttons.print.min.js"></script>



    <script>
        $(document).ready(function () {
            $('#companies').dataTable({
                buttons: {
                    buttons: ['copy', 'csv', 'excel']
                }
            });
        })
    </script>

}

src/Web/NetPhlixDB.Web/Views/Companies/Details.cshtml
@model NetPhlixDb.Data.ViewModels.Companies.CompanyViewModel

@{
    ViewData["Title"] = "Company Details";
}

<div class="container w-75">
    <h2 class="text-center mb-4 mt-4 text-info">@Model.Name - Details</h2>
    <div class="d-flex">
        <div class="col">
            <div class="row mx-auto">
                <div class="col-md-3">
                    <p>Company name:</p>
                </div>
                <div class="col">
                    <p class="font-weight-bold">@Model.Name</p>
                </div>
            </div>
            <div class="row mx-auto">
                <div class="col-md-3">
                    <p>Established:</p>
                </div>
                <div class="col">
                    <p class="font-weight-bold">@Model.CreatedOn.ToString("MMM/d/yyyy")</p>
                </div>
            </div>
            <div class="row mx-auto">
                <div class="col-md-3">
                    <p>Details:</p>
                </div>
                <div class="col">
                    <p class="font-weight-bold">@Model.Details</p>
                </div>
            </div>
        </div>
        <div class="col">
            <img class="img-fluid" src="@Model.Logo" alt="@Model.Name" style="height: 150px; width: 150px" />
        </div>
    </div>
    <h4 class="text-center mt-4 mb-4">Company Movies</h4>
    @if (!Model.CompanyMoviesViewModels.Any())
    {
        <p class="font-italic text-center">This company has no movies yet.</p>
    }
    else
    {
        foreach (var m in Model.CompanyMoviesViewModels)
        {
            <div class="col">
                <a asp-controller="Movies" asp-action="Details" asp-route-id="@m.Id"><img class="img-fluid" style="height: 72px; width: 60px" src="@m.Poster" /></a>
                <a asp-controller="Movies" asp-action="Details" asp-route-id="@m.Id">@m.Title (@m.DateReleased.ToString("yyyy"))</a>
            </div>
        }
    }
    <div class="text-center">
        <a class="btn btn-primary w-25 mt-2 mb-2" href="##" onClick="history.go(-1); return false;">Back</a>
    </div>
</div>